version: 2
updates:
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '13:30'
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
