name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: gradle test
        run: ./gradlew test
      - name: gradle check
        if: success()
        run: ./gradlew check
      - name: Build with Gradle
        run: ./gradlew build
      - name: Start docker container
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
