name: Release Drafter

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Create and Publish Container Image"]
    types: [completed]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}